documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: '**/README.txt'

Avalonia:
  - changed-files:
    - any-glob-to-any-file: SnapX.Avalonia/**

Core:
  - changed-files:
    - any-glob-to-any-file: SnapX.Core/**

enhancement:
  - head-branch: ['^feat', 'feat', 'feature']

actions:
  - changed-files:
    - any-glob-to-any-file: .github/workflows/**
    - any-glob-to-any-file: .github/labeler.yml

packaging:
  - changed-files:
    - any-glob-to-any-file: packaging/**

dependencies:
  - head-branch: ['^dep', 'dep', '^deps', 'deps', '^depend', 'depend', 'dependency', 'dependencies']

build:
  - changed-files:
    - any-glob-to-any-file: build/**
linux:
  - changed-files:
    - any-glob-to-any-file: SnapX.Core/Linux.props
windows:
  - changed-files:
    - any-glob-to-any-file: SnapX.Core/Windows.props
macOS:
  - changed-files:
    - any-glob-to-any-file: SnapX.Core/OSX.props
