using System.Text.RegularExpressions;
using System.Xml.Linq;

internal partial class XamlToGtkBuilder
{
    private static string PascalToKebab(string input)
    {
        return MyRegex().Replace(input, "-$1").ToLower();
    }
    public static string ConvertXamlToGtk(string xaml)
    {
        var doc = XDocument.Parse(xaml);
        var gtkXml = new XElement("interface",
            new XElement("requires", new XAttribute("lib", "gtk"), new XAttribute("version", "4.0"))
        );

        foreach (var element in doc.Elements())
        {
            var attributes = string.Join(", ", element.Attributes().Select(a => $"{a.Name.LocalName}=\"{a.Value}\""));
            Console.WriteLine($"Processing element {element.Name.LocalName} with attributes [{attributes}]");
            gtkXml.Add(ConvertElement(element));
        }

        return $"""
                <?xml version="1.0" encoding="UTF-8"?>
                <!--
                DO NOT EDIT!
                This file was @generated by XAMLFORGTK. Instead, edit the
                corresponding .xaml file and regenerate this file with XAMLGEN.
                -->
                {gtkXml}
                """;
    }
    private static Dictionary<string, int> _idCounts = new();

    private static string GetUniqueId(string baseName)
    {
        if (!_idCounts.ContainsKey(baseName))
        {
            _idCounts[baseName] = 0;
            return baseName;
        }

        _idCounts[baseName]++;
        return $"{baseName}{_idCounts[baseName]}";
    }

    private static XElement ConvertElement(XElement xamlElement)
    {
        var rootElementLikely = false;
        var gtkClass = xamlElement.Name.LocalName switch
        {
            "AppWindow" => "GtkApplicationWindow",
            "Window" => "GtkWindow",
            "Box" => "GtkBox",
            "Widget" => "GtkWidget",
            "Button" => "GtkButton",
            "Label" => "GtkLabel",
            "TextBlock" => "GtkLabel",
            "StackPanel" => "GtkBox",
            "Grid" => "GtkGrid",
            "Entry" => "GtkEntry",
            "SplitView" => "GtkPaned",
            "Image" => "GtkImage",
            _ => xamlElement.Name.LocalName
        };
        if (gtkClass is "GtkApplicationWindow" or "GtkWindow") rootElementLikely = true;
        var uniqueId = GetUniqueId(xamlElement.Attribute("Name")?.Value ?? xamlElement.Name.LocalName);

        var gtkElement = new XElement("object",
            new XAttribute("class", gtkClass),
            new XAttribute("id", uniqueId)
        );
        var attributes = string.Join(", ", xamlElement.Attributes().Select(a => $"{a.Name.LocalName}=\"{a.Value}\""));
        Console.WriteLine($"Processing element {xamlElement.Name.LocalName} with attributes [{attributes}]");
        List<XElement> styleClasses = [];
        List<XElement> properties = [];
        string? childType = null;

        foreach (var attr in xamlElement.Attributes())
        {
            if (gtkClass == "GtkGrid")
            {
                switch (attr.Name.LocalName)
                {
                    case "RowDefinitions":
                    {
                        var rowDefs = attr.Value.Split(',');
                        for (var i = 0; i < rowDefs.Length; i++)
                        {
                            var rowType = rowDefs[i].Trim();
                            var rowElement = new XElement("property",
                                new XAttribute("name", "row")
                            );
                            rowElement.Value = $"{i}";

                            if (rowType == "*")
                            {
                                rowElement.Add(new XAttribute("hexpand", "true"));
                            }

                            // gtkElement.Add(rowElement);
                        }

                        continue;
                    }
                    case "Row":
                        gtkElement.Add(new XElement("property",
                            new XAttribute("name", "top-attach"),
                            attr.Value
                        ));
                        continue;
                    case "Column":
                        gtkElement.Add(new XElement("property",
                            new XAttribute("name", "left-attach"),
                            attr.Value
                        ));
                        continue;
                    case "RowSpan":
                        gtkElement.Add(new XElement("property",
                            new XAttribute("name", "height"),
                            attr.Value
                        ));
                        continue;
                    case "ColumnSpan":
                        gtkElement.Add(new XElement("property",
                            new XAttribute("name", "width"),
                            attr.Value
                        ));
                        continue;
                }
            }

            var gtkProp = attr.Name.LocalName switch
            {
                "Text" => "label",
                "Clicked" => "signal",
                "VerticalAlignment" => "valign",
                "Width" => "default-width",
                "Height" => "default-height",
                "MinWidth" => "width-request",
                "MinHeight" => "height-request",
                "ChildType" => "child-type",

                _ => PascalToKebab(attr.Name.LocalName)
            };
            var value = attr.Value;
            if (value is "Center") value = "3";
            if (value is "Vertical") value = "1";
            if (gtkProp is "child-type") childType = attr.Value;
            switch (gtkProp)
            {
                case "xmlns" or "x" or "child-type" or "grid.-row":
                case "class" when rootElementLikely:
                    continue;
                default:
                    switch (gtkProp)
                    {
                        case "style":
                            styleClasses.AddRange(attr.Value.Split(',').Select(styleClass => new XElement("class", new XAttribute("name", styleClass.Trim()))));
                            continue;
                        case "margin":
                        {
                            var margins = attr.Value.Split([' ', ','], StringSplitOptions.RemoveEmptyEntries)
                                .Select(int.Parse).ToArray();

                            switch (margins.Length)
                            {
                                case 1:
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-top"), margins[0]));
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-bottom"), margins[0]));
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-start"), margins[0]));
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-end"), margins[0]));
                                    break;
                                case 2:
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-top"), margins[1]));
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-bottom"), margins[1]));
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-start"), margins[0]));
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-end"), margins[0]));
                                    break;
                                case 4:
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-top"), margins[0]));
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-end"), margins[1]));
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-bottom"), margins[2]));
                                    properties.Add(new XElement("property", new XAttribute("name", "margin-start"), margins[3]));
                                    break;
                            }

                            continue;
                        }
                    }

                    gtkElement.Add(gtkProp == "signal"
                        ? new XElement("signal", new XAttribute("name", "clicked"), new XAttribute("handler", value))
                        : new XElement("property", new XAttribute("name", gtkProp), value));
                    break;
            }
        }


        if (styleClasses.Count != 0)
        {
            gtkElement.Add(new XElement("style", styleClasses));
        }

        gtkElement.Add(properties);
        List<XElement> childElements = [];

        foreach (var child in xamlElement.Elements())
        {
            var childGtkElement = ConvertElement(child);
            var childWrapper = new XElement("child", childGtkElement);

            if (childType != null)
            {
                childWrapper.SetAttributeValue("type", childType);
                childType = null;
            }

            childElements.Add(childWrapper);
        }
        gtkElement.Add(childElements);

        return gtkElement;
    }

    [GeneratedRegex("(?<!^)([A-Z])")]
    private static partial Regex MyRegex();
}
