name: Build On Other Arches

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

# This workflow is triggered automatically by ./build.yml (as Github Actions) after a Arch Linux run.
# This was done to bypass GitHub's UI. I don't want to see these architectures building when I'm doing builds.
# They take a long time thanks to cross compilation & QEMU and slow down Nightly.link builds being updated.

on:
  workflow_dispatch:

jobs:
  windows_arm64:
    timeout-minutes: 3000
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Publish Windows ARM64 (CLI)
        working-directory: SnapX.CLI
        run: dotnet publish -c ${{ matrix.configuration }} -r win-arm64 -p:UseCurrentRuntimeIdentifier=true
      - name: Publish Windows ARM64 (Avalonia)
        working-directory: SnapX.Avalonia
        run: dotnet publish -c ${{ matrix.configuration }} -r win-arm64 -p:UseCurrentRuntimeIdentifier=true
      - name: Upload ARM64 Publish artifact (CLI)
        uses: actions/upload-artifact@v4
        with:
          name: SnapX-CLI-${{ matrix.configuration }}-${{ runner.os }}-ARM64
          path: "SnapX.CLI/bin/${{ matrix.configuration }}/net9.0/win-arm64/publish"
          compression-level: 9
          if-no-files-found: error
      - name: Upload ARM64 Publish artifact (Avalonia)
        uses: actions/upload-artifact@v4
        with:
          name: SnapX-Avalonia-${{ matrix.configuration }}-${{ runner.os }}-ARM64
          path: "SnapX.Avalonia/bin/${{ matrix.configuration }}/net9.0/win-arm64/publish"
          compression-level: 9
          if-no-files-found: error
