name: Build SnapX

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"

permissions:
  contents: read

jobs:
  alpine:
    name: Alpine Build
    runs-on: ${{matrix.os}}
    timeout-minutes: 360
    env:
      ALLOW_DOTNET_DOWNLOAD: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]
        configuration:
          - Release
          - Debug
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Alpine Linux
        uses: bgilbert/setup-alpine@aarch64
        with:
          packages: >
            clang
            curl
            bash
            build-base
            libunwind-dev
            xz-dev
            zlib-dev
            icu-libs

      - name: Download API keys
        env:
          API_KEYS: ${{ secrets.API_KEYS }}
        if: env.API_KEYS != ''
        shell: alpine.sh {0}
        run: |
          set -euo pipefail
          curl -fsSL "$API_KEYS" -o SnapX.Core/Upload/APIKeysLocal.cs
      - name: Remove version requirement
        run: rm global.json
        shell: alpine.sh {0}
      - name: Remove GCC
        run: apk del gcc
        shell: alpine.sh {0}
      - name: Publish
        run: ./build.sh --configuration ${{ matrix.configuration }}
        shell: alpine.sh {0}
      - name: Build
        run: ./build.sh tarball --configuration ${{ matrix.configuration }} --assembly snapx-ui
        shell: alpine.sh {0}
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: SnapX-Avalonia-${{ matrix.configuration }}-${{ runner.os }}-musl-${{ runner.arch }}
          path: "SnapX-UI*"
          if-no-files-found: error
  rpms:
    name: RPMs
    runs-on: ${{matrix.os}}
    timeout-minutes: 360
    container:
      image: ${{ matrix.container }}
    env:
      ALLOW_DOTNET_DOWNLOAD: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm ]

        container: [ fedora:rawhide, fedora:43, fedora:42, fedora:41 ]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup environment
        run: |
          dnf -y upgrade --refresh
          dnf -y install git rpmdevtools rpm-build libicu
      - name: Build RPM
        id: build_rpm
        env:
          API_KEYS: ${{ secrets.API_KEYS }}
        run: |
          cd packaging
          dnf builddep -y snapx.spec
          spectool -g -R snapx.spec
          rpmdev-setuptree
          rpmbuild -ba snapx.spec | tee rpmbuild.log
          # Extract all lines starting with "Wrote:" and get the file paths
          grep '^Wrote:' rpmbuild.log | awk '{print $2}' > rpm_files.txt

          # Print the paths for debugging
          cat rpm_files.txt

          # Save the list as an output for the next step
          echo "rpm_paths=$(paste -sd ' ' rpm_files.txt)" >> $GITHUB_OUTPUT
      - name: Format Container Name
        id: format
        run: |
          CONTAINER_NAME="${{ matrix.container }}"
          formattedName=$(echo "${CONTAINER_NAME}" | awk -F: '{
            printf "%s", toupper(substr($1,1,1)) tolower(substr($1,2)) "-" toupper(substr($2,1,1)) tolower(substr($2,2))
          }')
          echo "formattedName=${formattedName}" >> "$GITHUB_OUTPUT"
      - name: Upload artifact (RPM - Release on Linux)
        uses: actions/upload-artifact@v5
        with:
          name: SnapX-RPM-${{ steps.format.outputs.formattedName }}-${{ runner.arch }}
          path: /github/home/rpmbuild/**/*.rpm
          if-no-files-found: error
  build:
    name: Build
    runs-on: ${{matrix.os}}
    timeout-minutes: 65
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-24.04-arm, macos-26, macos-15-intel, windows-2025, windows-11-arm ]
        configuration:
          - Release
          - Debug
        exclude:
          - os: windows-11-arm
            configuration: Debug

    env:
      SOLUTION_FILE_PATH: SnapX.slnx
      ASSEMBLY_INFO_PATH: Directory.build.props

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Free Disk Space (Ubuntu)
        if: runner.os == 'Linux'
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: false
          dotnet: false
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x.x
      - name: Restore
        run: dotnet restore --packages ./vendor SnapX.slnx
      - name: Restore build project
        run: dotnet restore --packages ./vendor build/build.csproj
      - name: Cache .NET NuGet packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-${{ runner.arch }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-nuget-
      - name: Install NativeAOT Linux Deps
        if: runner.os == 'Linux'
        run: "sudo apt update && sudo apt install -y clang zlib1g-dev"
      - name: Install Rust toolchain
        if: runner.os == 'macOS'
        run: brew install rust
#      - name: 🔷 Update Flatpak Sources
#        if: ${{ matrix.configuration == 'Debug' && runner.os == 'Linux' && runner.arch == 'X64' && !startsWith(github.ref, 'refs/heads/dep/') }}
#        run: |
#          sudo apt install -y flatpak flatpak-builder
#          flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
#          flatpak install --user -y org.freedesktop.Sdk//25.08 org.freedesktop.Sdk.Extension.dotnet9//25.08
#          dotnet tool install --global Nickvision.FlatpakGenerator --version 2025.1.0
#          flatpak-dotnet-generator SnapX.Avalonia/SnapX.Avalonia.csproj -o packaging/flathub/sources.json -d vendor --no-self-contained --user
#          flatpak-dotnet-generator build/build.csproj -o packaging/flathub/build-sources.json -d vendor --no-self-contained --user
#      - name: 📦 Commit Flatpak Sources
#        if: ${{ matrix.configuration == 'Debug' && runner.os == 'Linux' && runner.arch == 'X64' && !startsWith(github.ref, 'refs/heads/dep/') }}
#        uses: EndBug/add-and-commit@v9
#        continue-on-error: true
#        with:
#          add: "packaging/flathub/*.json"
#          commit: "--no-verify --no-gpg-sign"
#          push: "--no-verify --no-signed"
#          message: "build(flathub): update nuget vendor sources [skip ci]"
      - name: Install xmlstarlet
        if: matrix.configuration == 'Debug' && runner.os == 'Linux'
        run: sudo apt install -y xmlstarlet
      - name: Update fallback version
        if: matrix.configuration == 'Debug' && runner.os == 'Linux' && always()
        continue-on-error: true
        run: |
          raw_version=$(./build.sh --version | grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.\+]+)?')
          fallback_version=$(echo "$raw_version" | sed 's/-.*//')
          echo "Fallback version: $fallback_version"
          sed -i "s|<Version>.*</Version>|<Version>${fallback_version}</Version>|" Directory.Build.props
      - name: Commit fallback version
        if: matrix.configuration == 'Debug' && runner.os == 'Linux' && runner.arch == 'X64' && always()
        continue-on-error: true
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Extract the new fallback version from the props file
          fallback_version=$(grep -oP '(?<=<Version>).*?(?=</Version>)' Directory.Build.props)

          # Check if there are any changes
          if ! git diff --quiet Directory.Build.props; then
            git pull --ff-only
            git add Directory.Build.props
            git commit -m "chore(release): update fallback version to ${fallback_version}" --no-verify
            git push --no-verify
          else
            echo "No changes to commit."
          fi
      - name: 🛠 Generate NuGet.config
        if: matrix.configuration == 'Debug' && runner.os == 'Linux'
        run: |
          printf '%s\n' \
            '<?xml version="1.0" encoding="utf-8"?>' \
            '<configuration>' \
            '  <packageSources>' \
            '    <clear />' \
            '    <add key="Local" value="vendor" />' \
            '  </packageSources>' \
            '</configuration>' > NuGet.config
      - name: 🛠 Ensure RestorePackagesPath in Directory.Build.props
        if: matrix.configuration == 'Debug' && runner.os == 'Linux'
        run: |
          FILE="Directory.Build.props"
          PATH_NODE="//Project/PropertyGroup/RestorePackagesPath"
          # If file exists and node is missing, insert it
          if [ -f "$FILE" ]; then
            if ! xmlstarlet sel -t -v "$PATH_NODE" "$FILE" 2>/dev/null | grep -q .; then
              echo "🔧 Inserting <RestorePackagesPath>vendor</RestorePackagesPath>..."
              xmlstarlet ed --inplace \
                -s "//Project/PropertyGroup[1]" -t elem -n "RestorePackagesPath" -v "vendor" \
                "$FILE"
            else
              echo "✅ RestorePackagesPath already set."
            fi
          else
            echo "❌ Directory.Build.props does not exist. Cannot insert RestorePackagesPath for Vendored build. Build will FAIL."
            exit 1
          fi
      # Packagers: This vendored source does not have the APIKeys SnapX uses.
      # I cannot provide them in public source code.
      - name: Upload Source With Dependencies
        if: matrix.configuration == 'Debug' && runner.os == 'Linux'
        uses: actions/upload-artifact@v5
        with:
          name: SnapX-Vendored-Source-${{ runner.arch }}
          path: .
          include-hidden-files: false
      - name: Download API keys
        env:
          API_KEYS: ${{ secrets.API_KEYS }}
        if: env.API_KEYS != ''
        shell: bash
        run: |
          set -euo pipefail
          curl -fsSL "$API_KEYS" -o SnapX.Core/Upload/APIKeysLocal.cs
#      - name: Enforce code style using dotnet format
#        if: matrix.configuration == 'Debug' && runner.os == 'Linux' && runner.arch == 'X64'
#        run: |
#          dotnet format --verify-no-changes -v diagnostic SnapX.slnx \
#            --include $(find . -type f -name '*.cs' ! -path './build/*' ! -path './SnapX.Core/Upload/APIKeysLocal.cs')
      - name: Publish
        if: runner.os == 'Windows'
        run: ./build.ps1 --configuration ${{ matrix.configuration }}
      - name: Publish
        if: runner.os != 'Windows'
        run: ./build.sh --configuration ${{ matrix.configuration }}
      - name: Assemble SnapX UI Tarball
        if: matrix.configuration == 'Release' && runner.os == 'Linux'
        run: "./build.sh tarball --assembly snapx-ui"
      - name: Assemble SnapX CLI Tarball
        if: matrix.configuration == 'Release' && runner.os == 'Linux'
        run: "./build.sh tarball --assembly snapx"
      - name: Upload artifact (CLI - Release on Linux)
        if: matrix.configuration == 'Release' && runner.os == 'Linux'
        uses: actions/upload-artifact@v5
        with:
          name: SnapX-CLI-${{ matrix.configuration }}-${{ runner.os }}-${{ runner.arch }}
          path: "SnapX-CLI*"
          compression-level: 9
          if-no-files-found: error

      - name: Upload artifact (CLI - Non-Release or non-Linux)
        if: matrix.configuration != 'Release' || runner.os != 'Linux'
        uses: actions/upload-artifact@v5
        with:
          name: SnapX-CLI-${{ matrix.configuration }}-${{ runner.os }}-${{ runner.arch }}
          path: "Output/snapx"
          compression-level: 9
          if-no-files-found: error
      - name: Upload artifact (Avalonia - Release on Linux)
        if: matrix.configuration == 'Release' && runner.os == 'Linux'
        uses: actions/upload-artifact@v5
        with:
          name: SnapX-Avalonia-${{ matrix.configuration }}-${{ runner.os }}-${{ runner.arch }}
          path: "SnapX-UI*"
          compression-level: 9
          if-no-files-found: error

      - name: Upload artifact (Avalonia - Non-Release or non-Linux)
        if: matrix.configuration != 'Release' || runner.os != 'Linux'
        uses: actions/upload-artifact@v5
        with:
          name: SnapX-Avalonia-${{ matrix.configuration }}-${{ runner.os }}-${{ runner.arch }}
          path: "Output/snapx-ui"
          compression-level: 9
          if-no-files-found: error
