name: Lint Commit Messages
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Ensure commit message(s) is/are compliant (conventional commits via commitlint)
        uses: wagoid/commitlint-github-action@v6
        with:
          commitDepth: 1
