name: Lint Markdown Files
on: [push, pull_request]
  
permissions:
  contents: write
  pull-requests: write

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          fix: true
          globs: '**/*.md'
